In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

from sklearn.ensemble import RandomForestRegressor

C:\Users\priya bhosale\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [3]:
df=pd.read_csv("IMDb Movies India.csv",encoding="latin")
print(df)

                                     Name    Year Duration            Genre  \
0                                             NaN      NaN            Drama
1      #Gadhvi (He thought he was Gandhi)  (2019)  109 min            Drama
2                             #Homecoming  (2021)   90 min   Drama, Musical
3                                 #Yaaram  (2019)  110 min  Comedy, Romance
4                       ...And Once Again  (2010)  105 min            Drama
...                                   ...     ...      ...              ...
15504                 Zulm Ko Jala Doonga  (1988)      NaN           Action
15505                               Zulmi  (1999)  129 min    Action, Drama
15506                           Zulmi Raj  (2005)      NaN           Action
15507                       Zulmi Shikari  (1988)      NaN           Action
15508                        Zulm-O-Sitam  (1998)  130 min    Action, Drama

       Rating Votes            Director           Actor 1             Actor 2  \
0         NaN   NaN       J.S. Randhawa          Manmauji              Birbal
1         7.0     8       Gaurav Bakshi      Rasika Dugal      Vivek Ghamande
2         NaN   NaN  Soumyajit Majumdar      Sayani Gupta   Plabita Borthakur
3         4.4    35          Ovais Khan           Prateik          Ishita Raj
4         NaN   NaN        Amol Palekar      Rajat Kapoor  Rituparna Sengupta
...       ...   ...                 ...               ...                 ...
15504     4.6    11       Mahendra Shah  Naseeruddin Shah       Sumeet Saigal
15505     4.5   655          Kuku Kohli      Akshay Kumar      Twinkle Khanna
15506     NaN   NaN          Kiran Thej   Sangeeta Tiwari                 NaN
15507     NaN   NaN                 NaN               NaN                 NaN
15508     6.2    20        K.C. Bokadia        Dharmendra          Jaya Prada

               Actor 3
0      Rajendra Bhatia
1        Arvind Jangid
2           Roy Angana
3      Siddhant Kapoor
4          Antara Mali
...                ...
15504    Suparna Anand
15505      Aruna Irani
15506              NaN
15507              NaN
15508      Arjun Sarja

[15509 rows x 10 columns]

In [4]:
print("print first 5 values")
print(df.head())

print("\nInformation")
print(df.info())

print("missing value")
print(df.isnull().sum())

print first 5 values
                                 Name    Year Duration            Genre  \
0                                         NaN      NaN            Drama
1  #Gadhvi (He thought he was Gandhi)  (2019)  109 min            Drama
2                         #Homecoming  (2021)   90 min   Drama, Musical
3                             #Yaaram  (2019)  110 min  Comedy, Romance
4                   ...And Once Again  (2010)  105 min            Drama

   Rating Votes            Director       Actor 1             Actor 2  \
0     NaN   NaN       J.S. Randhawa      Manmauji              Birbal
1     7.0     8       Gaurav Bakshi  Rasika Dugal      Vivek Ghamande
2     NaN   NaN  Soumyajit Majumdar  Sayani Gupta   Plabita Borthakur
3     4.4    35          Ovais Khan       Prateik          Ishita Raj
4     NaN   NaN        Amol Palekar  Rajat Kapoor  Rituparna Sengupta

           Actor 3
0  Rajendra Bhatia
1    Arvind Jangid
2       Roy Angana
3  Siddhant Kapoor
4      Antara Mali

Information
<class 'pandas.DataFrame'>
RangeIndex: 15509 entries, 0 to 15508
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      15509 non-null  str
 1   Year      14981 non-null  str
 2   Duration  7240 non-null   str
 3   Genre     13632 non-null  str
 4   Rating    7919 non-null   float64
 5   Votes     7920 non-null   str
 6   Director  14984 non-null  str
 7   Actor 1   13892 non-null  str
 8   Actor 2   13125 non-null  str
 9   Actor 3   12365 non-null  str
dtypes: float64(1), str(9)
memory usage: 2.3 MB
None
missing value
Name           0
Year         528
Duration    8269
Genre       1877
Rating      7590
Votes       7589
Director     525
Actor 1     1617
Actor 2     2384
Actor 3     3144
dtype: int64

In [5]:
df = df.dropna(subset=["Rating"])
df

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
1,#Gadhvi (He thought he was Gandhi),(2019),109 min,Drama,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid
3,#Yaaram,(2019),110 min,"Comedy, Romance",4.4,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor
5,...Aur Pyaar Ho Gaya,(1997),147 min,"Comedy, Drama, Musical",4.7,827,Rahul Rawail,Bobby Deol,Aishwarya Rai Bachchan,Shammi Kapoor
6,...Yahaan,(2005),142 min,"Drama, Romance, War",7.4,"1,086",Shoojit Sircar,Jimmy Sheirgill,Minissha Lamba,Yashpal Sharma
8,?: A Question Mark,(2012),82 min,"Horror, Mystery, Thriller",5.6,326,Allyson Patel,Yash Dave,Muntazir Ahmad,Kiran Bhatia
...,...,...,...,...,...,...,...,...,...,...
15501,Zulm Ki Hukumat,(1992),NaN,"Action, Crime, Drama",5.3,135,Bharat Rangachary,Dharmendra,Moushumi Chatterjee,Govinda
15503,Zulm Ki Zanjeer,(1989),125 min,"Action, Crime, Drama",5.8,44,S.P. Muthuraman,Chiranjeevi,Jayamalini,Rajinikanth
15504,Zulm Ko Jala Doonga,(1988),NaN,Action,4.6,11,Mahendra Shah,Naseeruddin Shah,Sumeet Saigal,Suparna Anand
15505,Zulmi,(1999),129 min,"Action, Drama",4.5,655,Kuku Kohli,Akshay Kumar,Twinkle Khanna,Aruna Irani
15508,Zulm-O-Sitam,(1998),130 min,"Action, Drama",6.2,20,K.C. Bokadia,Dharmendra,Jaya Prada,Arjun Sarja

In [6]:
'''Fill Missing Values'''
df["Genre"] = df["Genre"].fillna("Unknown")
df["Director"] = df["Director"].fillna("Unknown")
df["Actor 1"] = df["Actor 1"].fillna("Unknown")
df["Actor 2"] = df["Actor 2"].fillna("Unknown")
df["Actor 3"] = df["Actor 3"].fillna("Unknown")
print(df.isnull().sum())

Name           0
Year           0
Duration    2068
Genre          0
Rating         0
Votes          0
Director       0
Actor 1        0
Actor 2        0
Actor 3        0
dtype: int64

In [7]:
'''Clean Year'''
df["Year"] = df["Year"].str.extract("(\d{4})")
df["Year"] = pd.to_numeric(df["Year"], errors="coerce")
df["Year"] = df["Year"].fillna(df["Year"].median())
df

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
1,#Gadhvi (He thought he was Gandhi),2019,109 min,Drama,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid
3,#Yaaram,2019,110 min,"Comedy, Romance",4.4,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor
5,...Aur Pyaar Ho Gaya,1997,147 min,"Comedy, Drama, Musical",4.7,827,Rahul Rawail,Bobby Deol,Aishwarya Rai Bachchan,Shammi Kapoor
6,...Yahaan,2005,142 min,"Drama, Romance, War",7.4,"1,086",Shoojit Sircar,Jimmy Sheirgill,Minissha Lamba,Yashpal Sharma
8,?: A Question Mark,2012,82 min,"Horror, Mystery, Thriller",5.6,326,Allyson Patel,Yash Dave,Muntazir Ahmad,Kiran Bhatia
...,...,...,...,...,...,...,...,...,...,...
15501,Zulm Ki Hukumat,1992,NaN,"Action, Crime, Drama",5.3,135,Bharat Rangachary,Dharmendra,Moushumi Chatterjee,Govinda
15503,Zulm Ki Zanjeer,1989,125 min,"Action, Crime, Drama",5.8,44,S.P. Muthuraman,Chiranjeevi,Jayamalini,Rajinikanth
15504,Zulm Ko Jala Doonga,1988,NaN,Action,4.6,11,Mahendra Shah,Naseeruddin Shah,Sumeet Saigal,Suparna Anand
15505,Zulmi,1999,129 min,"Action, Drama",4.5,655,Kuku Kohli,Akshay Kumar,Twinkle Khanna,Aruna Irani
15508,Zulm-O-Sitam,1998,130 min,"Action, Drama",6.2,20,K.C. Bokadia,Dharmendra,Jaya Prada,Arjun Sarja

In [8]:
'''Clean Duration'''
df["Duration"] = df["Duration"].str.replace(" min", "", regex=False)
df["Duration"] = pd.to_numeric(df["Duration"], errors="coerce")
df["Duration"] = df["Duration"].fillna(df["Duration"].median())
df

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
1,#Gadhvi (He thought he was Gandhi),2019,109.0,Drama,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid
3,#Yaaram,2019,110.0,"Comedy, Romance",4.4,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor
5,...Aur Pyaar Ho Gaya,1997,147.0,"Comedy, Drama, Musical",4.7,827,Rahul Rawail,Bobby Deol,Aishwarya Rai Bachchan,Shammi Kapoor
6,...Yahaan,2005,142.0,"Drama, Romance, War",7.4,"1,086",Shoojit Sircar,Jimmy Sheirgill,Minissha Lamba,Yashpal Sharma
8,?: A Question Mark,2012,82.0,"Horror, Mystery, Thriller",5.6,326,Allyson Patel,Yash Dave,Muntazir Ahmad,Kiran Bhatia
...,...,...,...,...,...,...,...,...,...,...
15501,Zulm Ki Hukumat,1992,134.0,"Action, Crime, Drama",5.3,135,Bharat Rangachary,Dharmendra,Moushumi Chatterjee,Govinda
15503,Zulm Ki Zanjeer,1989,125.0,"Action, Crime, Drama",5.8,44,S.P. Muthuraman,Chiranjeevi,Jayamalini,Rajinikanth
15504,Zulm Ko Jala Doonga,1988,134.0,Action,4.6,11,Mahendra Shah,Naseeruddin Shah,Sumeet Saigal,Suparna Anand
15505,Zulmi,1999,129.0,"Action, Drama",4.5,655,Kuku Kohli,Akshay Kumar,Twinkle Khanna,Aruna Irani
15508,Zulm-O-Sitam,1998,130.0,"Action, Drama",6.2,20,K.C. Bokadia,Dharmendra,Jaya Prada,Arjun Sarja

In [9]:
'''Clean Votes'''
df["Votes"] = df["Votes"].str.replace(",", "", regex=False)
df["Votes"] = pd.to_numeric(df["Votes"], errors="coerce")
df["Votes"] = df["Votes"].fillna(df["Votes"].median())
df

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
1,#Gadhvi (He thought he was Gandhi),2019,109.0,Drama,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid
3,#Yaaram,2019,110.0,"Comedy, Romance",4.4,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor
5,...Aur Pyaar Ho Gaya,1997,147.0,"Comedy, Drama, Musical",4.7,827,Rahul Rawail,Bobby Deol,Aishwarya Rai Bachchan,Shammi Kapoor
6,...Yahaan,2005,142.0,"Drama, Romance, War",7.4,1086,Shoojit Sircar,Jimmy Sheirgill,Minissha Lamba,Yashpal Sharma
8,?: A Question Mark,2012,82.0,"Horror, Mystery, Thriller",5.6,326,Allyson Patel,Yash Dave,Muntazir Ahmad,Kiran Bhatia
...,...,...,...,...,...,...,...,...,...,...
15501,Zulm Ki Hukumat,1992,134.0,"Action, Crime, Drama",5.3,135,Bharat Rangachary,Dharmendra,Moushumi Chatterjee,Govinda
15503,Zulm Ki Zanjeer,1989,125.0,"Action, Crime, Drama",5.8,44,S.P. Muthuraman,Chiranjeevi,Jayamalini,Rajinikanth
15504,Zulm Ko Jala Doonga,1988,134.0,Action,4.6,11,Mahendra Shah,Naseeruddin Shah,Sumeet Saigal,Suparna Anand
15505,Zulmi,1999,129.0,"Action, Drama",4.5,655,Kuku Kohli,Akshay Kumar,Twinkle Khanna,Aruna Irani
15508,Zulm-O-Sitam,1998,130.0,"Action, Drama",6.2,20,K.C. Bokadia,Dharmendra,Jaya Prada,Arjun Sarja

In [10]:
''' Encode Categorical Columns'''
le = LabelEncoder()

df["Genre"] = le.fit_transform(df["Genre"])
df["Director"] = le.fit_transform(df["Director"])
df["Actor 1"] = le.fit_transform(df["Actor 1"])
df["Actor 2"] = le.fit_transform(df["Actor 2"])
df["Actor 3"] = le.fit_transform(df["Actor 3"])
df

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
1,#Gadhvi (He thought he was Gandhi),2019,109.0,268,7.0,8,811,1782,2815,377
3,#Yaaram,2019,110.0,207,4.4,35,1749,1589,890,2572
5,...Aur Pyaar Ho Gaya,1997,147.0,177,4.7,827,2005,508,85,2449
6,...Yahaan,2005,142.0,331,7.4,1086,2643,931,1388,3030
8,?: A Question Mark,2012,82.0,367,5.6,326,174,2521,1461,1205
...,...,...,...,...,...,...,...,...,...,...
15501,Zulm Ki Hukumat,1992,134.0,28,5.3,135,500,631,1436,868
15503,Zulm Ki Zanjeer,1989,125.0,28,5.8,44,2339,550,936,2014
15504,Zulm Ko Jala Doonga,1988,134.0,0,4.6,11,1418,1405,2536,2725
15505,Zulmi,1999,129.0,38,4.5,655,1338,145,2670,371
15508,Zulm-O-Sitam,1998,130.0,38,6.2,20,1171,631,934,355

In [11]:
'''Features and Target ,"Year","Duration","Votes",  '''
X = df[["Genre","Director","Actor 1","Actor 2","Actor 3"]]
y = df["Rating"]

'''Train-Test Split'''
X_train, X_test, y_train, y_test = train_test_split( X,y,test_size=0.20,random_state=42)

'''Train Model'''
model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [12]:
'''Prediction'''
y_pred = model.predict(X_test)

In [13]:
'''Evaluation'''
print("\nModel Performance")

print("Mean Absolute Error :", mean_absolute_error(y_test, y_pred))

print("Mean Squared Error :", mean_squared_error(y_test, y_pred))

print("R2 Score :", r2_score(y_test, y_pred))

Model Performance
Mean Absolute Error : 1.0232461700336701
Mean Squared Error : 1.6475792115856485
R2 Score : 0.11379742465064835

In [14]:
'''Compare Actual vs Predicted'''
result = pd.DataFrame({
    "Actual Rating": y_test,
    "Predicted Rating": y_pred
})

print("\nActual vs Predicted Ratings")

print(result.head(10))

Actual vs Predicted Ratings
       Actual Rating  Predicted Rating
9456             3.3             5.278
14816            5.3             5.762
3213             5.7             5.539
3778             7.2             6.400
5775             3.5             4.568
12203            7.2             6.179
12305            3.8             5.654
4650             6.9             6.373
8701             5.2             6.096
4707             7.4             6.012

In [15]:
'''Predict One Sample Movie'''
sample = X_test.iloc[[0]]

prediction = model.predict(sample)

print("\nActual Rating :", y_test.iloc[0])
print("Predicted Rating :", prediction[0])

Actual Rating : 3.3
Predicted Rating : 5.277999999999999